### ISSUE TITLE
Getting "Electron Error" (TypeError: Log.log is not a function)

### ISSUE THREAD

**Issue by Dresch360** [chicohernando/MMM-Peloton#1]
[2021-01-31 01:12:18.387] [LOG]    Connecting socket for: MMM-Peloton
[2021-01-31 01:12:18.387] [ERROR]  App threw an error during load
[2021-01-31 01:12:18.388] [ERROR]  TypeError: Log.log is not a function
    at Class.start (/home/pi/MagicMirror/modules/MMM-Peloton/node_helper.js:7:7)
    at /home/pi/MagicMirror/js/app.js:230:18
    at new Server (/home/pi/MagicMirror/js/server.js:84:3)
    at /home/pi/MagicMirror/js/app.js:223:18
    at loadNextModule (/home/pi/MagicMirror/js/app.js:172:5)
    at /home/pi/MagicMirror/js/app.js:167:6
    at Class.loaded (/home/pi/MagicMirror/js/node_helper.js:19:3)
    at loadModule (/home/pi/MagicMirror/js/app.js:148:6)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:165:5)
    at /home/pi/MagicMirror/js/app.js:167:6
[2021-01-31 01:12:18.389] [LOG]    Whoops! There was an uncaught exception...
[2021-01-31 01:12:18.390] [ERROR]  TypeError: Log.log is not a function
    at Class.start (/home/pi/MagicMirror/modules/MMM-Peloton/node_helper.js:7:7)
    at /home/pi/MagicMirror/js/app.js:230:18
    at new Server (/home/pi/MagicMirror/js/server.js:84:3)
    at /home/pi/MagicMirror/js/app.js:223:18
    at loadNextModule (/home/pi/MagicMirror/js/app.js:172:5)
    at /home/pi/MagicMirror/js/app.js:167:6
    at Class.loaded (/home/pi/MagicMirror/js/node_helper.js:19:3)
    at loadModule (/home/pi/MagicMirror/js/app.js:148:6)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:165:5)
    at /home/pi/MagicMirror/js/app.js:167:6
[2021-01-31 01:19:40.289] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2021-01-31 01:19:40.290] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[2021-01-31 01:19:40.307] [LOG]    Whoops! There was an uncaught exception...
[2021-01-31 01:19:40.308] [ERROR]  Error: listen EADDRINUSE: address already in use 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (net.js:1226:14)
    at listenInCluster (net.js:1274:12)
    at doListen (net.js:1413:7)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 8080

**Comment by chicohernando** [comment]
@dresch27 -- I'm going to start looking into this today, can you tell me which version of MagicMirror you are using?
```sh
grep version package.json
"version": "2.13.0",
```

**Comment by chicohernando** [comment]
@dresch27 -- I believe I have resolved the issue in the linked PR.  Can you do a `git pull` and try again and let me know if it works?

**Comment by Dresch360** [comment]
Thank you so much! It works now. You've built really great module!!
