### ISSUE TITLE
module_not_found

### ISSUE THREAD

**Issue by scottdsauer** [chicohernando/MMM-Peloton#5]
getting error, I checked install and code, seems to be ok.  Any ideas?

> magicmirror@2.18.0 start
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[23.01.2022 08:45.25.609] [LOG]   Starting MagicMirror: v2.18.0
[23.01.2022 08:45.25.619] [LOG]   Loading config ...
[23.01.2022 08:45.25.625] [LOG]   Loading module helpers ...
[23.01.2022 08:45.25.627] [LOG]   No helper found for module: alert.
[23.01.2022 08:45.25.645] [LOG]   Initializing new module helper ...
[23.01.2022 08:45.25.646] [LOG]   Module helper loaded: updatenotification
[23.01.2022 08:45.25.648] [LOG]   No helper found for module: clock.
[23.01.2022 08:45.25.651] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Peloton/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
[23.01.2022 08:45.25.653] [LOG]   Loading module helpers ...
[23.01.2022 08:45.25.654] [LOG]   No helper found for module: alert.
[23.01.2022 08:45.25.655] [LOG]   Initializing new module helper ...
[23.01.2022 08:45.25.656] [LOG]   Module helper loaded: updatenotification
[23.01.2022 08:45.25.657] [LOG]   No helper found for module: clock.
[23.01.2022 08:45.25.659] [ERROR] App threw an error during load
[23.01.2022 08:45.25.662] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Peloton/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Peloton/node_helper.js:1:15)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
[23.01.2022 08:45.25.663] [ERROR] Whoops! There was an uncaught exception...
[23.01.2022 08:45.25.669] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Peloton/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Peloton/node_helper.js:1:15)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-Peloton/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[23.01.2022 08:45.25.671] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[23.01.2022 08:45.25.672] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[23.01.2022 08:45.26.016] [LOG]   Launching application.
^C/home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT

**Comment by jschless** [comment]
You need to install the request library. In the MMM-Peloton directory, run the following command:
`npm install request`

That ought to do it.

**Comment by scottdsauer** [comment]
Was this in the installation instructions and I just didnt read, if so I
apologize for bothering you for something stupiid and trivial.

**Comment by scottdsauer** [comment]
That worked!  thank you so much for writing this!
